### PR TITLE
Set max line length for js

### PR DESCRIPTION
**Pull request by thewinterwind**
@liangshan @imlazyone 

In order to avoid developers adding very long lines of javascript, which has already happened in our legacy codebase, I propose we set a limit for max length in js.

### CODE REVIEW

**Comment by imlazyone** [comment]
@liangshan @HouCoder @RichardLee1978 what do you guys think? 100 ok?

**Comment by liangshan** [comment]
First, for PHP and Python it's 80.

Second, I think we have to discuss this with indent.

+ 4 space indent makes it difficult to hit 80
+ I'd like 2 space indent with 80, 4 with a little longer, maybe 100 and 110 will work

**Comment by imlazyone** [comment]
I think in the current Airbnb javascript style guide it's 2 spaces.

**Comment by imlazyone** [comment]
@thewinterwind this conversation is pending for too long.

Let's go with 80 first.

**Comment by thewinterwind** [comment]
@imlazyone @liangshan Im ok with 80 characters.

On the new juwai project we are using 4 spaces indentation which is the default for JS Beautifier. I've always used 4 spaces, two seems not enough.

**Comment by thewinterwind** [comment]
updated to 80 chars

**Comment by liangshan** [comment]
2 space and 80 chars, i'm OK with that.
closing.

**Pull request merged**
