### PR TITLE
[NES-66] Provide suggested changes to the documentation to make it mo…

### PR DESCRIPTION
**Pull request by dppereyra**
## Summary of changes

* Moved deadline entry to No feedback actions entry.
* Changed the deadline entry to refer to the issue priority entry
* Fix issue priority broken link.

Above changes will make it more clear about deadlines and non feedbacks. 

/fyi: @agirivera: Please review.

### CODE REVIEW

**Comment by imlazyone** [comment]
Awsome. 💯

**Comment by imlazyone** [comment]
Is this related to https://github.com/juwai/style-guide/issues/41 ?

**Comment by arkhi** [comment]
Perfect. :)

**Comment by arkhi** [comment]
Thanks @dppereyra!

**Pull request merged**
