### PR TITLE
[style-guide-issues-38] Added Tool for Python

### PR DESCRIPTION
**Pull request by stefcloud**
## Summary of changes

- Added Tool link for Python. 

/fyi: @juwai/platform-all @juwai/frontend : Please review.

### CODE REVIEW

**Comment by tjoelsson** [comment]
Is there a tool you can install for local development?

**Comment by stefcloud** [comment]
@tjoelsson , I installed [pep8](https://pypi.python.org/pypi/pep8) in my local.

**Comment by tjoelsson** [comment]
So how about linking to this tool instead? The description under the Tools header suggests the tools are things you can install for your editor.

**Comment by stefcloud** [comment]
@tjoelsson , Changed the link.

**Comment by tjoelsson** [comment]
👍

**Comment by stefcloud** [comment]
@wanleung @mryder It would be great if you can check this. :)

**Comment by mryder** [comment]
We can also discuss using pyflakes/pylint if we want additional coverage for Python standards. pep8 is good and probably doesn't need a discussion though.

👍

**Comment by stefcloud** [comment]
Thank you @mryder and @tjoelsson. 

@tjoelsson , can you merge this for me? Thanks again.

**Pull request merged**
