### PR TITLE
Proposal for writing user stories

### PR DESCRIPTION
**Pull request by arkhi**
@tjoelsson and @imlazyone: This is the beginning of the “user story” page.

I hope it can be enhanced later, for example with the rules we have about what user story is eligible to be added to a sprint, our policy about having mid–sprint stories and its consequences, etc.

### CODE REVIEW

**Comment by imlazyone** [comment]
Looks good but my only concern is - is this PR appropriate for this open source repo?

**Comment by arkhi** [comment]
@imlazyone: Why would it be not? :)

From my perspective:

1. These are style–guides about how to write user stories, so the repository “style–guide” seems like the right place.
1. This is a workflow we can document and make public.
1. Not all people involved in making User Stories have a github account.

**Comment by imlazyone** [comment]
Ok make sense. 

:+1:

**Comment by tjoelsson** [comment]
:cyclone:

**Pull request merged**
