### PR TITLE
[GITHUB-57] documentation for newbies

### PR DESCRIPTION
**Pull request by arkhi**
Following @HouCoder [comment in another PR](https://github.com/juwai/in-house/pull/69#discussion-diff-61014845), I‘m updating the documentation to reflect our decisions about defects deadlines for feedback.

### CODE REVIEW

**Comment by arkhi** [comment]
@juwai/all: This PR is waiting for comments or thumbs…

**Comment by tjoelsson** [comment]
💯

**Comment by mark-juwai** [comment]
👍

**Comment by arkhi** [comment]
Thanks guys. Merging!

**Pull request merged**
