### PR TITLE
Remove Quote object properties for JavaScript

### PR DESCRIPTION
**Pull request by HouCoder**
## Summary of changes

- Remove Quote object properties for JavaScript

## How to Test

No quote properties in [this commit](https://github.com/HouCoder/style-guide/blob/0fcf96a945c87039c915634e9eaa371d273ed6d0/language-javascript.md).

/fyi: @juwai/frontend: Please review.

### CODE REVIEW

**Comment by monochrome-yeh** [comment]
563ee7d8141692058004751864_700wa_0

**Comment by monochrome-yeh** [comment]
@juwai/frontend , kindly have a look.

**Comment by imlazyone** [comment]
👍

**Comment by HouCoder** [comment]
Oh man, you are alive, @imlazyone .

**Comment by imlazyone** [comment]
👯

**Pull request merged**
