### PR TITLE
Use alternative syntax for control structures

### PR DESCRIPTION
**Pull request by arkhi**
## Summary of changes

We have this choice between two syntaxes. I believe it makes more sense to use the alternative syntax when dealing with template, for the reasons explained in the PR.

I assigned two people from the two teams as this will impact multiple products.

### CODE REVIEW

**Comment by mark-juwai** [comment]
Any context? Did it cause any problem?
Personally, I don't see big difference two ways. And I prefer blade syntaxes, looks cleaner. :)

**Comment by cpanganiban** [comment]
@arkhi in connection with what @mark-juwai said, does this also applies to Laravel-Based sites?

**Comment by johndavedecano** [comment]
Blade template no longer has <?php ?>. However its a good practice that.

1.  No one will ever declare a variable on blade templates.
2.  Blade template has one responsibility and that is just to present the data given by the controller. Nothing more.

**Comment by piadelosreyes** [comment]
We can apply the alternative syntax for control structure in agent-admin but in the long run we cannot use it because we should maximized the usage of the framework.

**Comment by arkhi** [comment]
> Any context? Did it cause any problem?

I don’t think it caused problems so far, it’s just easier to read. I take it as a general rule that it’s a good thing to separate concerns between technologies or languages.

> And I prefer blade syntaxes, looks cleaner. :)

I agree; I don’t think we can use `<?php` in blade file. :)

**Comment by johndavedecano** [comment]
@arkhi Yes <?php ?> is working at blade templates but its not a good practice...

**Comment by mark-juwai** [comment]
```
<?php if (true) { ?>
......
<?php } ?>
```
```
<?php if (true) : ?>
......
<?php endif; ?>
```
If you are talking about these two ways, I absolutely support the second one.

**Comment by arkhi** [comment]
> If you are talking about these two ways, I absolutely support the second one.

We are. :)

**Comment by mark-juwai** [comment]
>Any context? Did it cause any problem?

That's the context I was asking. 😄 

Then could you add the opposite side example to be like: first way is no good, we prefer second one. In case of someone stupid like me think it's comparing to blade syntaxes. 😆

**Comment by arkhi** [comment]
> Then could you add the opposite side example to be like: first way is no good, we prefer second one. In case of someone stupid like me think it's comparing to blade syntaxes.

Very good idea. I’ll do that. Thanks. :)

(Don’t be stupid, you’re not stupid!)

**Comment by arkhi** [comment]
@mark-juwai: I added examples. We might use this format for future PR with examples if you guys agree.

**Comment by mark-juwai** [comment]
👍

**Comment by cpanganiban** [comment]
I'm fine with this

slack for ios upload-8

**Comment by arkhi** [comment]
Thanks for the feedback!

**Pull request merged**
